# Resource Configuration for atlantis-java-main CRS Deployment
#
# This configuration supports:
# 1. Multiple workers with per-worker resource specifications
# 2. Per-CRS resource constraints (fine-grained control)
# 3. Even resource distribution when CRS-specific configs are omitted
# 4. Flexible LLM resource allocation (total budget divided among CRSs)

# Worker definitions - specify available resources on each worker
workers:
  local:
    cpuset: "0-15"  # Taskset CPU list
    memory: "16G"

# Global LLM configuration (applies to all CRSs combined)
# These are TOTAL limits that will be divided among CRSs
llm:
  max_budget: 10  # Total budget in dollars for ALL CRSs
  max_rpm: 1200    # Total requests per minute, each CRS could go up to this
  max_tpm: 1000000 # Total tokens per minute, each CRS could go up to this

# CRS-specific configurations
# If a CRS is not listed here, it will get an even share of remaining resources
crs:
  # Configuration for atlantis-java-main CRS
  atlantis-java-main:
    # Worker placement - CRS will be deployed to these workers
    workers:
      - local
