# Mixed Configuration Example
# Some CRSs with explicit resources, others use remaining capacity

workers:
  local:
    cpu: 16
    memory: 32G
  server1:
    cpu: 32
    memory: 64G
  server2:
    cpu: 64
    memory: 128G

# Global LLM configuration
llm:
  max_budget: 200
  max_rpm: 2000
  max_tpm: 2000000

crs:
  # High-priority CRS with explicit allocation
  atlantis-c-libafl:
    workers:
      - server1
    resources:
      server1:
        cpu: 20
        memory: 40G
    llm:
      max_budget: 100  # Gets half the budget
      max_rpm: 1000
      max_tpm: 1000000

  # Medium-priority CRS with explicit allocation
  atlantis-multilang:
    workers:
      - server2
    resources:
      server2:
        cpu: 32
        memory: 64G
    llm:
      max_budget: 60
      max_rpm: 600
      max_tpm: 600000

  # Low-priority CRS - gets remaining resources
  atlantis-python:
    workers:
      - local
    # No explicit resources - gets what's left
    # Remaining budget: 200 - 100 - 60 = $40
    # Remaining RPM: 2000 - 1000 - 600 = 400
    # Remaining TPM: 2000000 - 1000000 - 600000 = 400000

  # Another low-priority CRS - shares remaining with atlantis-python
  atlantis-java:
    workers:
      - server2
    # Shares remaining resources with atlantis-python
    # Budget: $20 (half of remaining $40)
    # RPM: 200 (half of remaining 400)
    # TPM: 200000 (half of remaining 400000)
