# Resource Configuration for Multi-Worker CRS Deployment
#
# This configuration supports:
# 1. Multiple workers with per-worker resource specifications
# 2. Per-CRS resource constraints (fine-grained control)
# 3. Even resource distribution when CRS-specific configs are omitted
# 4. Flexible LLM resource allocation (total budget divided among CRSs)

# Worker definitions - specify available resources on each worker
workers:
  local:
    cpuset: "0-15"  # Taskset CPU list
    memory: "32G"
  server1:
    cpuset: "0-31"  # Taskset CPU list
    memory: "64G"
  server2:
    cpuset: "0-63"  # Taskset CPU list
    memory: "128G"

# Global LLM configuration (applies to all CRSs combined)
# These are TOTAL limits that will be divided among CRSs
llm:
  max_budget: 100  # Total budget in dollars for ALL CRSs
  max_rpm: 1200    # Total requests per minute, each CRS could go up to this
  max_tpm: 1000000 # Total tokens per minute, each CRS could go up to this

# CRS-specific configurations
# If a CRS is not listed here, it will get an even share of remaining resources
crs:
  # Fine-grained configuration example
  atlantis-c:
    # Worker placement - CRS will be deployed to these workers
    workers:
      - local
      - server1

    # Per-worker resource allocation
    # If omitted, resources are divided evenly across specified workers
    resources:
      local:
        cpuset: "0-3"  # Taskset CPU list
        memory: "4G"
      server1:
        cpuset: "0-7"  # Taskset CPU list
        memory: "8G"

    # LLM resources for THIS specific CRS (optional)
    # If omitted, gets even share from global llm config
    llm:
      max_budget: 30  # This CRS gets $30 of the total budget
      max_rpm: 1200   # This CRS gets is allowed to go up to global max_rpm
      max_tpm: 300000 # This CRS gets 300k TPM

  # Simplified configuration example
  atlantis-multilang:
    workers:
      - server2

    # Single resource spec applies to all workers
    resources:
      cpuset: "0-9"  # Taskset CPU list
      memory: "64G"

    # No LLM specified - will get even share of remaining global budget

  # Minimal configuration example
  atlantis-java:
    workers:
      - local
      - server2
    # Resources specified for each worker
    resources:
      local:
        cpuset: "4-7"  # Taskset CPU list
        memory: "4G"
      server2:
        cpuset: "10-13"  # Taskset CPU list
        memory: "64G"
    # No LLM specified - will get even share of remaining global budget
